### ISSUE TITLE
error beim start der Version 0.0.19

### ISSUE THREAD

**Issue by Matten-Matten** [TA2k/ioBroker.mercedesme#11]
```

2020-01-06 20:10:25.066 - info: host.ioBroker-RasPi object change system.adapter.mercedesme.0
--
2020-01-06 20:10:25.146 - info: host.ioBroker-RasPi instance system.adapter.mercedesme.0 started with pid 3743
2020-01-06 20:10:25.491 - error: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.mercedesme/main.js:1401
2020-01-06 20:10:25.491 - error: Caught by controller[0]: } catch {
2020-01-06 20:10:25.491 - error: Caught by controller[0]: ^
2020-01-06 20:10:25.491 - error: Caught by controller[0]: SyntaxError: Unexpected token {
2020-01-06 20:10:25.491 - error: Caught by controller[0]: at createScript (vm.js:80:10)
2020-01-06 20:10:25.491 - error: Caught by controller[0]: at Object.runInThisContext (vm.js:139:10)
2020-01-06 20:10:25.491 - error: Caught by controller[0]: at Module._compile (module.js:617:28)
2020-01-06 20:10:25.491 - error: Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
2020-01-06 20:10:25.491 - error: Caught by controller[0]: at Module.load (module.js:566:32)
2020-01-06 20:10:25.492 - error: Caught by controller[0]: at tryModuleLoad (module.js:506:12)
2020-01-06 20:10:25.492 - error: Caught by controller[0]: at Function.Module._load (module.js:498:3)
2020-01-06 20:10:25.492 - error: Caught by controller[0]: at Function.Module.runMain (module.js:694:10)
2020-01-06 20:10:25.492 - error: Caught by controller[0]: at startup (bootstrap_node.js:204:16)
2020-01-06 20:10:25.492 - error: Caught by controller[0]: at bootstrap_node.js:625:3
2020-01-06 20:10:25.492 - error: host.ioBroker-RasPi instance system.adapter.mercedesme.0 terminated with code 1 ()
2020-01-06 20:10:25.492 - info: host.ioBroker-RasPi Restart adapter system.adapter.mercedesme.0 because enabled


```

**Comment by TA2k** [comment]
mit version 0.0.20 gefixt
