### ISSUE TITLE
Extremely high CPU loads caused by adapter

### ISSUE THREAD

**Issue by MrIngenieur** [TA2k/ioBroker.mercedesme#213]
**Describe the bug**  
This morning the Adapter went offline, so that i needed to get new tokens. 
After token update it worked for a while, but now CPU-Load goes to 100% when MercedesMe Adapter is running. 

**To Reproduce**  
1. Go to iobroker/instances
2. Click on MercedesMe.0 start
3. wait for a while (2-3 minutes)
5. Click on MercedesMe.0 stop

**Expected behavior**  
No unusual CPU Loads from the adapter

**Screenshots & Logfiles**  
![IMG_0360](https://github.com/TA2k/ioBroker.mercedesme/assets/113664053/3ef26395-884c-485f-9b53-bf79c730cc14)
If applicable, add screenshots and logfiles to help explain your problem.
![IMG_0361](https://github.com/TA2k/ioBroker.mercedesme/assets/113664053/1140ae79-202d-4d1b-83fd-eabce8977fda)

**Versions:**  
 - Adapter version: 0.1.8
 - JS-Controller version:5.0.19 
 - Node version: v18.20.1
 - Operating system: Linux iobroker 6.6.20+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64

**Additional context**  
As long as adapter is active, CPU load is super high. When adapter is switched off, everything goes back to normal.

**Comment by TA2k** [comment]
Any information in the log
can you execute the command top in the shell of the host machine

**Comment by MrIngenieur** [comment]
![IMG_0363](https://github.com/TA2k/ioBroker.mercedesme/assets/113664053/56068d2d-fd30-4931-af6f-72465b5f57ca)

**Comment by TA2k** [comment]
In the iobroker admin under log or protokolle
is the cpu load the whole time high in top?

**Comment by MrIngenieur** [comment]
No, i pretty much fluctuates

**Comment by MrIngenieur** [comment]
`Lost websocket connection` several times

```

2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.382  - [31merror[39m: mercedesme.0 (4714) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-04-07 19:46:19.382  - [31merror[39m: mercedesme.0 (4714) unhandled promise rejection: DB closed
2024-04-07 19:46:19.384  - [31merror[39m: mercedesme.0 (4714) Error: DB closed
    at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24)
    at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)
    at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:521:40)
    at Mercedesme._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5537:76)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
2024-04-07 19:46:19.384  - [31merror[39m: mercedesme.0 (4714) DB closed
2024-04-07 19:46:19.385  - [31merror[39m: mercedesme.0 (4714) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-04-07 19:46:19.385  - [31merror[39m: mercedesme.0 (4714) unhandled promise rejection: DB closed
2024-04-07 19:46:19.386  - [31merror[39m: mercedesme.0 (4714) Error: DB closed
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)

2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.376  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) Could not perform strict object check of state mercedesme.0.W1NGM2BB3PA028210.history.tankLevelStatus: DB closed
2024-04-07 19:46:19.377  - [33mwarn[39m: mercedesme.0 (4714) get state error: Connection is closed.
2024-04-07 19:46:19.382  - [31merror[39m: mercedesme.0 (4714) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-04-07 19:46:19.382  - [31merror[39m: mercedesme.0 (4714) unhandled promise rejection: DB closed
2024-04-07 19:46:19.384  - [31merror[39m: mercedesme.0 (4714) Error: DB closed
    at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24)
    at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)
    at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:521:40)
    at Mercedesme._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5537:76)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
2024-04-07 19:46:19.384  - [31merror[39m: mercedesme.0 (4714) DB closed
2024-04-07 19:46:19.385  - [31merror[39m: mercedesme.0 (4714) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-04-07 19:46:19.385  - [31merror[39m: mercedesme.0 (4714) unhandled promise rejection: DB closed
2024-04-07 19:46:19.386  - [31merror[39m: mercedesme.0 (4714) Error: DB closed
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)

```

**Comment by MrIngenieur** [comment]
```

2024-04-07 21:57:18.303	debug	update for xxxxxxxx: 0

mercedesme.1
2024-04-07 21:57:18.216	debug	update for xxxxxx: 0

mercedesme.1
2024-04-07 21:57:15.263	debug	{"message":"app twin actor has stopped"}

mercedesme.1
2024-04-07 21:57:15.263	debug	{"message":"app twin actor is stopping"}

mercedesme.1
2024-04-07 21:57:15.262	debug	{"message":"app twin actor ttl was reached"}

```

**Comment by TA2k** [comment]
Error: DB closed is a sign for hdd failure you should check your sd card

**Comment by LastPerfectTobi** [comment]
On my system is the same problem maybe caused by the mercedesme adapter. 

I was not able to get a Logfile yet. 
But I saw in "htop" that mercedesme got a high cpu usage and directly after that the iobroker.js-controller got much over 100% CPU usage. 

When I stop mercedesme adapter everything works fine. 

Maybe you can help to get a logfile.
And if possible in german 🙂

**Comment by MrIngenieur** [comment]
> Error: DB closed is a sign for hdd failure you should check your sd card

I don’t have an SD card running. 
System is on NVMe SSD running totally stable as long as Mercedes Me adapter is switched off.

**Comment by MrIngenieur** [comment]
> On my system is the same problem maybe caused by the mercedesme adapter.
> 
> I was not able to get a Logfile yet. But I saw in "htop" that mercedesme got a high cpu usage and directly after that the iobroker.js-controller got much over 100% CPU usage.
> 
> When I stop mercedesme adapter everything works fine.
> 
> Maybe you can help to get a logfile. And if possible in german 🙂

That describes my observations 100%

**Comment by chris-woy** [comment]
I have the same problem since this night, mercedesme causes high cpu usage so that javascript stopped working correctly.
I had to stop mercedesme

**Comment by TA2k** [comment]
Any suspicious logs?

**Comment by MrIngenieur** [comment]
Maybe there’s also a problem on the Mercedes Backend… 
I also use EVCC and the Mercedes Integration is also broken since today. 
But iobroker managed to run some hours longer than EVCC integration in my case.

**Comment by bloop16** [comment]
Seams that i also have got Problems with the Adapter.
Getting message: Websocket closed every 5min. CPU load also got higher.


```
2024-04-07 21:54:27.857 - debug: mercedesme.0 (3962631) Received State Updated
2024-04-07 21:54:27.862 - debug: mercedesme.0 (3962631) Received State Updated
2024-04-07 21:54:27.863 - debug: mercedesme.0 (3962631) {"vinsList":["W1VVLAEZ5P4203066"]}
2024-04-07 21:54:27.873 - debug: mercedesme.0 (3962631) update for W1VVLAEZ5P4203066: 0
2024-04-07 21:54:27.880 - debug: mercedesme.0 (3962631) update for W1VVLAEZ5P4203066: 1
2024-04-07 21:54:27.920 - debug: mercedesme.0 (3962631) Received State Updated
2024-04-07 21:54:27.931 - debug: mercedesme.0 (3962631) {"vinsList":["W1VVLAEZ5P4203066"]}
2024-04-07 21:54:28.609 - debug: mercedesme.0 (3962631) update for W1VVLAEZ5P4203066: 1
2024-04-07 21:54:31.888 - debug: mercedesme.0 (3962631) 1006
2024-04-07 21:54:31.897 - debug: mercedesme.0 (3962631) Websocket closed
2024-04-07 21:55:27.931 - info: mercedesme.0 (3962631) Lost WebSocket connection. Reconnect WebSocket
2024-04-07 21:55:29.934 - debug: mercedesme.0 (3962631) Connect to WebSocket
2024-04-07 21:55:30.296 - debug: mercedesme.0 (3962631) WebSocket connected
```

**Comment by TA2k** [comment]
When you put the instance in log level debug is there a lot of updates happening?

**Comment by TA2k** [comment]
Die GitHub version versucht die reconnects zu minimieren bitte testen ob es Einfluss auf cpu usage hat

**Comment by MrIngenieur** [comment]
Ist die GitHub version neuer?
Ich verwende schon die 0.1.8 aus GitHub.

**Comment by TA2k** [comment]
version is gleich commit hash b78f0ad844ca0c0a1cc7526c0f0501443df9610c

**Comment by darkiop** [comment]
Kann das Problem bestätigen.

Kann das hier mit in Zusammenhang stehen?

https://github.com/ioBroker/socket-client/issues/23
https://forum.iobroker.net/post/1147767

**Comment by LastPerfectTobi** [comment]
> version is gleich commit hash b78f0ad844ca0c0a1cc7526c0f0501443df9610c

Kanns leider heute nicht mehr testen. 
Der Katze-Button funktioniert bei mir am Handy nicht mehr. 
Werds leider erst morgen am PC ausprobieren können.

**Comment by TA2k** [comment]
Installieren via GitHub geht mit admin 6.17.x nicht mehr erst wieder mit 6.15.x
gibt es denn ein socket client bei euch
```
cd /opt/iobroker
npm ls @iobroker/socket-client
```

**Comment by LastPerfectTobi** [comment]
> Installieren via GitHub geht mit admin 6.17.x nicht mehr erst wieder mit 6.15.x
> 
> gibt es denn ein socket client bei euch
> 
> ```
> 
> cd /opt/iobroker
> 
> npm ls @iobroker/socket-client
> 
> ```

Achso, dann tuts auch am PC nicht. 

```

pi@raspberrypi:~ $ cd /opt/iobroker
pi@raspberrypi:/opt/iobroker $ npm ls @iobroker/socket-client
iobroker.inst@2.0.3 /opt/iobroker
└── (empty)

pi@raspberrypi:/opt/iobroker $

```

**Comment by MrIngenieur** [comment]
pm ls @iobroker/socket-client
iobroker.inst@3.0.0 /opt/iobroker
`-- (empty)

**Comment by TA2k** [comment]
ich habe nochmal was in der GitHub version angepasst bitte nochmal via GitHub installieren

**Comment by MrIngenieur** [comment]
> ich habe nochmal was in der GitHub version angepasst bitte nochmal via GitHub installieren

Neueste Version die mir angezeigt wird ist die 0.1.8

```

$ iobroker url TA2k/ioBroker.mercedesme --host iobroker --debug
install TA2k/ioBroker.mercedesme
Installing TA2k/ioBroker.mercedesme... (System call)
upload [0] mercedesme.admin /opt/iobroker/node_modules/iobroker.mercedesme/admin/words.js words.js application/javascript
Process exited with code 0

``` 
Auch danach noch…

**Comment by schlaubstar** [comment]
Ich hab das selbe Problem. System ist ein Pi3B mit Raspbian (Bullseye). Die 0.1.8er Version von GitHub lief seit Monaten ohne Probleme aber ich habe gestern ein Update via APT auf OS Level gemacht und folgendes wurde aktualisiert:

Upgrade: 
libblkid-dev:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
libsmartcols1:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
libmount-dev:ar                                    
mhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
libmount1:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
util-linux:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
fdisk:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
libfdisk1:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
**nodejs:armhf (18.20.0-1 nodesource1, 18.20.1-1nodesource1),** 
libuuid1:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
uuid-dev:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2 ), 
rfkill:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
mount:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
libblkid1:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2), 
bsdutils:armhf (1:2.36.1-8+deb11u1, 1:2.36.1-8+deb11u2), 
bsdextrautils:armhf (2.36.1-8+deb11u1, 2.36.1-8+deb11u2)
End-Date: 2024-04-06  22:36:24

Ich tippe mal auf das nodejs update, denn 3h danach hat sich der PI abgeschossen und tut es immer wieder, sobald ich mercedes.me aktiviere.

Ich habe die aktuellste Version von GitHub bereits installiert (0.1.8, 07.04.2024, 23:30h) aber das Problem bleibt bestehen.

**Comment by MrIngenieur** [comment]
> Problem bleibt bestehen.

Hier leider auch

**Comment by TA2k** [comment]
Ok nach der Installation wurde die Instanz neugestartet
Habe ich erstmal keine Ideen mehr woran es liegt

**Comment by TA2k** [comment]
Sind es denn alle  Pi3B mit Raspbian (Bullseye) mit node 18.20 ?

**Comment by TA2k** [comment]
Ich habe In der GitHub das schreiben der iobroker states deaktiviert einfach nochmal installieren

**Comment by schlaubstar** [comment]
Sieht erstmal ganz gut aus, besser als bei den Versionen vor Mitternacht. Allerdings trat bei mir das Problem gesichert erst nach einigen Stunden auf. Kann Dir morgen früh sagen, ob die Kiste abgebrannt ist, oder nicht ! ;-)

**Comment by MrIngenieur** [comment]
> Sind es denn alle Pi3B mit Raspbian (Bullseye) mit node 18.20 ?

Bei mir Pi5 mit neuestem PiOS und node 18.20

**Comment by TA2k** [comment]
habe noch Anpassung gemacht es scheint daran zu liegen das Mercedes viel öfters update liefert

**Comment by chris-woy** [comment]
Habe gerade die von GitHub neu installiert, ist jetzt Version 0.1.9
Anbindung an Mercedes läuft, CPU-Last bleibt niedrig
Log sieht ganz anders aus
Würde sagen PERFEKT

**Comment by MrIngenieur** [comment]
> habe noch Anpassung gemacht es scheint daran zu liegen das Mercedes viel öfters update liefert

Habe auch die 0.1.9 und sieht auf den ersten Blick auch stabiler aus. 
eine der beiden Instanz ging mal auf gelb, nach einem restart scheint es wieder zu funktionieren. 
also weiter beobachten. 
vielen dank schonmal für den nächtlichen Einsatz @TA2k

**Comment by klein0r** [comment]
> Kann das Problem bestätigen.
> 
> Kann das hier mit in Zusammenhang stehen?
> 
> [ioBroker/socket-client#23](https://github.com/ioBroker/socket-client/issues/23)
> 
> https://forum.iobroker.net/post/1147767

Nein, das sind ja nur Bibliotheken für den Client. Damit hat der Server nix zu tun.

**Comment by chris-woy** [comment]
Leider zu früh gefreut... Heut Morgen lief der Adapter noch perfekt, jetzt ist die Verbindung zu Mercedes gekappt. Das Log zeigt immer weiter 
1006
Websocket closed
Connect to Websocket
WS error:Error: Unexpected server response: 428

Vielleicht ein Problem/Änderung bei Mercedes?


[Bildschirmfoto 2024-04-08 um 10.08.22.pdf](https://github.com/TA2k/ioBroker.mercedesme/files/14902711/Bildschirmfoto.2024-04-08.um.10.08.22.pdf)

**Comment by TA2k** [comment]
bitte mal die 0.2.0 testen

**Comment by MrIngenieur** [comment]
> bitte mal die 0.2.0 testen

Bei mir ging die 0.1.9 auch nach einiger Zeit auf gelb. 
0.2.0 habe ich installiert, Prozessorlast ist bisher im normalen Bereich (ca. 5 Minuten uptime) und noch sind beide Instanzen auf grün. -> weiter beobachten

**Comment by chris-woy** [comment]
Mit der Version 0.2.0 ist zwar die CPU-Last gering, aber es gibt keine Kommunikation zu Mercedes

Es kommt auch kein "PONG" mehr


Hier das entsprechende LOG:

2024-04-08 12:44:16.923 - info: mercedesme.0 (10483) starting. Version 0.2.0 (non-npm: TA2k/ioBroker.mercedesme) in /opt/iobroker/node_modules/iobroker.mercedesme, node: v18.19.0, js-controller: 5.0.19
--
2024-04-08 12:44:17.023 - debug: mercedesme.0 (10483) Login
2024-04-08 12:44:17.025 - debug: mercedesme.0 (10483) refreshToken
2024-04-08 12:44:17.386 - debug: mercedesme.0 (10483) {"access_token":"XXXXX","refresh_token":"XXXXX","token_type":"Bearer","expires_in":7199}
2024-04-08 12:44:17.389 - debug: mercedesme.0 (10483) setRefrehToken: XXXXX
2024-04-08 12:44:17.390 - debug: mercedesme.0 (10483) Login successful
2024-04-08 12:44:17.391 - debug: mercedesme.0 (10483) start refresh interval
2024-04-08 12:44:17.732 - debug: mercedesme.0 (10483) {"assignedVehicles":[{"authorizationType":"USER","canReceiveVAC":true,"carline":"118","dealers":{"XXX"}]},"fin":"W1K1186XXX","isOwner":true,"isTemporarilyAccessible":false,"licensePlate":"XXX","mopf":false,"normalizedProfileControlSupport":"UNSUPPORTED","profileSyncSupport":"SUPPORTED","salesRelatedInformation":{"baumuster":{"baumuster":"1186861","baumusterDescription":"CLA 250 e Shooting Brake"},"line":{"code":"P59","description":""},"paint":{"code":"787","description":"mountaingrau metallic"},"upholstery":{"code":"101","description":"Ledernachbildung ARTICO schwarz"}},"tirePressureMonitoringType":"TirePressureMonitoring","trustLevel":3,"vehicleConnectivity":"BUILTIN","vehicleSegment":"DEFAULT","windowsLiftCount":"FourLift"}],"fleets":[]}
2024-04-08 12:44:17.733 - info: mercedesme.0 (10483) Found 1 vehicles
2024-04-08 12:44:17.734 - info: mercedesme.0 (10483) Creating vehicle XXX
2024-04-08 12:44:17.764 - debug: mercedesme.0 (10483) https://bff.emea-prod.mobilesdk.mercedes-benz.com//v1/vehicle/XXX/capabilities/commands
2024-04-08 12:44:17.789 - info: mercedesme.0 (10483) Start Websocket Connection
2024-04-08 12:44:17.791 - debug: mercedesme.0 (10483) Connect to WebSocket
2024-04-08 12:44:17.972 - error: mercedesme.0 (10483) WS error:Error: Unexpected server response: 428
2024-04-08 12:44:17.973 - debug: mercedesme.0 (10483) 1006
2024-04-08 12:44:17.973 - debug: mercedesme.0 (10483) Websocket closed
2024-04-08 12:44:18.023 - debug: mercedesme.0 (10483) {"commands":[{"additionalInformation":null,"XXX "SIGPOS_TYPE"}]}]}
2024-04-08 12:44:18.060 - debug: mercedesme.0 (10483) [{"activeTimes":{"begin":0,"days":[1,2,3,4,5,6,7],"end":1439},"id":2849361,"isActive":false,"name":"Heim","shape":{"circle":{"center":{"latitude":XXX,"longitude":XXX},"radius":18}},"violationType":"LEAVE_AND_ENTER"}]
2024-04-08 12:44:18.065 - debug: mercedesme.0 (10483) {" updatedAt”XXXX"2023-06-29T12:29:00.560Z"}
2024-04-08 12:45:02.792 - debug: mercedesme.0 (10483) Ping
2024-04-08 12:45:47.793 - debug: mercedesme.0 (10483) Ping
2024-04-08 12:46:32.794 - debug: mercedesme.0 (10483) Ping
2024-04-08 12:47:17.794 - debug: mercedesme.0 (10483) Ping
2024-04-08 12:48:02.794 - debug: mercedesme.0 (10483) Ping
2024-04-08 12:48:47.795 - debug: mercedesme.0 (10483) Ping
2024-04-08 12:49:17.792 - info: mercedesme.0 (10483) Try to reconnect
2024-04-08 12:49:17.793 - debug: mercedesme.0 (10483) Connect to WebSocket
2024-04-08 12:49:17.942 - error: mercedesme.0 (10483) WS error:Error: Unexpected server response: 428
2024-04-08 12:49:17.943 - debug: mercedesme.0 (10483) 1006
2024-04-08 12:49:17.945 - debug: mercedesme.0 (10483) Websocket closed
2024-04-08 12:50:02.794 - debug: mercedesme.0 (10483) Ping

**Comment by chris-woy** [comment]
Liegt an meiner IP-Adresse... Es scheint so, als ob der Mercedes-Server mich geblockt hat. Stelle ich die Verbindung über einen anderen Zugang her, dann läuft auch der Adapter wieder
Ist mir aufgefalle, da sich die App auch nicht mehr aktualisiert hat, es kamen nur noch Push-Mitteilungen

**Comment by TA2k** [comment]
Danke für den Hinweis habe den Hinweis in die 0.2.1 eingefügt.

**Comment by fuchs-1978** [comment]
Ich hatte auch die letzten zwei Tage Probleme mit hoher Last. Komischerweise war bei mir bei TOP immer der Javascript Adapter der Treiber. Allerdings hatte ich auch immer die Meldung des Mercedes Adapters, disconnect. Mal sehen ob es mit der neuen Version besser ist. Als Resultat habe ich mir heute eine neue VM aufgesetzt und alle Scripte durchgesehen. 🙈

**Comment by MrIngenieur** [comment]
> Meine Vermutung ist zur Zeit da auch die 0.1.8 korrekt laufen würde da mercedes wieder was geändert hat

also bei EVCC ist die mercedes Integration immer noch ohne Funktion. ioBroker mit 0.2.2 läuft aktuell bei mir stabil.

**Comment by darkiop** [comment]
> Ich hatte auch die letzten zwei Tage Probleme mit hoher Last. Komischerweise war bei mir bei TOP immer der Javascript Adapter der Treiber. Allerdings hatte ich auch immer die Meldung des Mercedes Adapters, disconnect. Mal sehen ob es mit der neuen Version besser ist. Als Resultat habe ich mir heute eine neue VM aufgesetzt und alle Scripte durchgesehen. 🙈

Den Effekt hatte ich auch. Teilweise hatte der javascript.0 >150000 input events, was dazu führte das javascript.0 und js-controller 100% CPU load hatten. Der Mercedes Me Adpater ist mir auch erst später als Ursache aufgefallen.

**Comment by MrIngenieur** [comment]
> > Meine Vermutung ist zur Zeit da auch die 0.1.8 korrekt laufen würde da mercedes wieder was geändert hat
> 
> 
> 
> also bei EVCC ist die mercedes Integration immer noch ohne Funktion. ioBroker mit 0.2.2 läuft aktuell bei mir stabil.

Heute um 11 Uhr gabs leider nochmal einen Aussetzer wo die CPU-Last wieder durch die Decke ging und die Werte nicht mehr aktualisiert wurden. 
Seit Restart ists im Moment wieder alles normal. 
![image](https://github.com/TA2k/ioBroker.mercedesme/assets/113664053/183b0e69-794f-4e76-983f-f921c0d8333f)

**Comment by Uwe1984** [comment]
> also bei EVCC ist die mercedes Integration immer noch ohne Funktion. ioBroker mit 0.2.2 läuft aktuell bei mir stabil.

Mercedes Integration in EVCC funktioniert wieder seit ein paar Wochen....

**Comment by MrIngenieur** [comment]
> > also bei EVCC ist die mercedes Integration immer noch ohne Funktion. ioBroker mit 0.2.2 läuft aktuell bei mir stabil.
> 
> 
> 
> Mercedes Integration in EVCC funktioniert wieder seit ein paar Wochen.... 

Kann ich nicht bestätigen. Seit einer Woche defekt. Ist hier allerdings auch nicht das Fokusthema.

**Comment by wendy2702** [comment]
Ist schon abzusehen wann die 0.2.2 im latest erscheint?

**Comment by TA2k** [comment]
Ist seit 6 Tagen drin

**Comment by wendy2702** [comment]
Ok.

Mal auf die Suche gehen. Wird mir nicht angezeigt.

Mal alles refreshen 

Danke

**Comment by wendy2702** [comment]
Hm,

Browser Cache gelöscht, Forced Reload, Refresh der Adapterseite, erneute Umstellung Latest --> Stable --> Latest ---> Kein MercedesMe update

![grafik](https://github.com/TA2k/ioBroker.mercedesme/assets/33424168/b23fcbad-656d-4c3c-8ba2-e7083667fe96)

Noch jemand eine Idee?
