### ISSUE TITLE
Adapter aktualisiert nicht

### ISSUE THREAD

**Issue by Matten-Matten** [TA2k/ioBroker.mercedesme#7]
Moin,

Der Adapter aktualisiert nicht im eingestellten Intervall.
Lediglich einmal nach dem Adapter Start werden die Werte aktualisiert, dann jedoch nicht mehr.

## Edit
gerade auch mit fehlermeldung:

```
2019-11-14 14:21:22.633 - info: mercedesme.0 States connected to redis: 127.0.0.1:6379
--
2019-11-14 14:21:22.784 - info: mercedesme.0 starting. Version 0.0.17 in /opt/iobroker/node_modules/iobroker.mercedesme, node: v8.12.0
2019-11-14 14:21:28.836 - error: mercedesme.0 uncaught exception: Cannot read property 'indexOf' of undefined
2019-11-14 14:21:28.837 - error: mercedesme.0 TypeError: Cannot read property 'indexOf' of undefined
at Request.request.post [as _callback] (/opt/iobroker/node_modules/iobroker.mercedesme/main.js:1713:15)
at self.callback (/opt/iobroker/node_modules/iobroker.mercedesme/node_modules/request/request.js:185:22)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at Request.onRequestError (/opt/iobroker/node_modules/iobroker.mercedesme/node_modules/request/request.js:881:8)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at TLSSocket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
at TLSSocket.emit (events.js:211:7)
2019-11-14 14:21:28.853 - info: mercedesme.0 terminating
2019-11-14 14:21:28.901 - error: Caught by controller[0]: TypeError: Cannot read property 'indexOf' of undefined
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at Request.request.post [as _callback] (/opt/iobroker/node_modules/iobroker.mercedesme/main.js:1713:15)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at self.callback (/opt/iobroker/node_modules/iobroker.mercedesme/node_modules/request/request.js:185:22)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at Request.emit (events.js:211:7)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at Request.onRequestError (/opt/iobroker/node_modules/iobroker.mercedesme/node_modules/request/request.js:881:8)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at ClientRequest.emit (events.js:211:7)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at TLSSocket.socketErrorListener (_http_client.js:387:9)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2019-11-14 14:21:28.902 - error: Caught by controller[0]: at TLSSocket.emit (events.js:211:7)
2019-11-14 14:21:28.902 - error: host.ioBroker-RasPi instance system.adapter.mercedesme.0 terminated with code 0 (OK)
```
nach erneutem Start, dann ohne Fehler.
Gruß
Matten Matten

**Comment by TA2k** [comment]
bitte mal über die webseite einloggen und schauen ob da fehler kommen
version via github neuinstallieren und checken ob da detailierte fehler kommen

**Comment by Matten-Matten** [comment]
Sorry bin leider nicht eher dazu gekommen.
```
mercedesme.0 | 2019-12-29 09:21:02.624 | error | {"code":"ACCESS_TOKEN_INVALID","message":"Provided token is expired","details":null}
-- | -- | -- | --
mercedesme.0 | 2019-12-29 09:21:02.624 | info | 401 Error try to refresh accesstoken.
```

**Comment by Matten-Matten** [comment]
aber momentan aktualisiert alles.

**Comment by Matten-Matten** [comment]
heute hatte ich folgendes im LOG

`2020-01-06 19:28:21.482 - error: mercedesme.0 null`

mehr leider nich habe den Adapter neu gestartet dann lief er wieder.

**Comment by TA2k** [comment]
Ich habe in der Version 0.0.19 noch ein paar sachen verbesser. da die server nicht sehr stabil sind

**Comment by Matten-Matten** [comment]
ok.
